# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0002_auto_20160416_1954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user1',
        ),
    ]
