# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0003_auto_20160416_2036'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
